name: Build affected packages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'next', 'canary']

jobs:
  main:
    runs-on: ubuntu-latest
    # Cancel any previous runs in progress
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3 --exclude='*,!tag:package'
      - run: npx nx affected -t test --parallel=3 --exclude='*,!tag:package'
      - run: npx nx affected -t build --parallel=10 --exclude='*,!tag:package'
      - run: npx nx run-many --target=test:e2e --projects=3000-home,3001-shop,3002-checkout --parallel=3
